package main

import (
	"fmt"

	hclog "github.com/hashicorp/go-hclog"
	"github.com/raito-io/cli/base"
	"github.com/raito-io/cli/base/info"
	"github.com/raito-io/cli/base/util/plugin"
	"github.com/raito-io/cli/base/wrappers"

	"cli-plugin-dbt/internal/constants"
)

var version = "0.0.0"

var logger hclog.Logger

func main() {
	logger = base.Logger()
	logger.SetLevel(hclog.Debug)

	err := base.RegisterPlugins(
		&info.InfoImpl{
			Info: &plugin.PluginInfo{
				Name:    "dbt",
				Version: plugin.ParseVersion(version),
				Parameters: []*plugin.ParameterInfo{
					{Name: constants.ManifestParameterName, Description: "The manifest.json file generated by dbt", Mandatory: true},
				},
				Type: []plugin.PluginType{
					plugin.PluginType_PLUGIN_TYPE_RESOURCE_PROVIDER,
					plugin.PluginType_PLUGIN_TYPE_TAG_SYNC,
				},
			},
		},
		wrappers.ResourceProviderSyncFactory(InitializeResourceProviderSyncer),
		wrappers.TagSyncFactory(InitializeTagSyncer),
	)

	if err != nil {
		logger.Error(fmt.Sprintf("error while registering plugins: %s", err.Error()))
	}
}
