// Code generated by mockery v2.42.0. DO NOT EDIT.

package resource_provider

import (
	context "context"

	schema "github.com/raito-io/sdk-go/types"
	mock "github.com/stretchr/testify/mock"

	services "github.com/raito-io/sdk-go/services"
)

// MockAccessProviderClient is an autogenerated mock type for the AccessProviderClient type
type MockAccessProviderClient struct {
	mock.Mock
}

type MockAccessProviderClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccessProviderClient) EXPECT() *MockAccessProviderClient_Expecter {
	return &MockAccessProviderClient_Expecter{mock: &_m.Mock}
}

// CreateAccessProvider provides a mock function with given fields: ctx, ap
func (_m *MockAccessProviderClient) CreateAccessProvider(ctx context.Context, ap schema.AccessProviderInput) (*schema.AccessProvider, error) {
	ret := _m.Called(ctx, ap)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccessProvider")
	}

	var r0 *schema.AccessProvider
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, schema.AccessProviderInput) (*schema.AccessProvider, error)); ok {
		return rf(ctx, ap)
	}
	if rf, ok := ret.Get(0).(func(context.Context, schema.AccessProviderInput) *schema.AccessProvider); ok {
		r0 = rf(ctx, ap)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schema.AccessProvider)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, schema.AccessProviderInput) error); ok {
		r1 = rf(ctx, ap)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccessProviderClient_CreateAccessProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccessProvider'
type MockAccessProviderClient_CreateAccessProvider_Call struct {
	*mock.Call
}

// CreateAccessProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - ap schema.AccessProviderInput
func (_e *MockAccessProviderClient_Expecter) CreateAccessProvider(ctx interface{}, ap interface{}) *MockAccessProviderClient_CreateAccessProvider_Call {
	return &MockAccessProviderClient_CreateAccessProvider_Call{Call: _e.mock.On("CreateAccessProvider", ctx, ap)}
}

func (_c *MockAccessProviderClient_CreateAccessProvider_Call) Run(run func(ctx context.Context, ap schema.AccessProviderInput)) *MockAccessProviderClient_CreateAccessProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(schema.AccessProviderInput))
	})
	return _c
}

func (_c *MockAccessProviderClient_CreateAccessProvider_Call) Return(_a0 *schema.AccessProvider, _a1 error) *MockAccessProviderClient_CreateAccessProvider_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccessProviderClient_CreateAccessProvider_Call) RunAndReturn(run func(context.Context, schema.AccessProviderInput) (*schema.AccessProvider, error)) *MockAccessProviderClient_CreateAccessProvider_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccessProvider provides a mock function with given fields: ctx, id, ops
func (_m *MockAccessProviderClient) DeleteAccessProvider(ctx context.Context, id string, ops ...func(*services.UpdateAccessProviderOptions)) error {
	_va := make([]interface{}, len(ops))
	for _i := range ops {
		_va[_i] = ops[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccessProvider")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...func(*services.UpdateAccessProviderOptions)) error); ok {
		r0 = rf(ctx, id, ops...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccessProviderClient_DeleteAccessProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccessProvider'
type MockAccessProviderClient_DeleteAccessProvider_Call struct {
	*mock.Call
}

// DeleteAccessProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - ops ...func(*services.UpdateAccessProviderOptions)
func (_e *MockAccessProviderClient_Expecter) DeleteAccessProvider(ctx interface{}, id interface{}, ops ...interface{}) *MockAccessProviderClient_DeleteAccessProvider_Call {
	return &MockAccessProviderClient_DeleteAccessProvider_Call{Call: _e.mock.On("DeleteAccessProvider",
		append([]interface{}{ctx, id}, ops...)...)}
}

func (_c *MockAccessProviderClient_DeleteAccessProvider_Call) Run(run func(ctx context.Context, id string, ops ...func(*services.UpdateAccessProviderOptions))) *MockAccessProviderClient_DeleteAccessProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*services.UpdateAccessProviderOptions), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*services.UpdateAccessProviderOptions))
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockAccessProviderClient_DeleteAccessProvider_Call) Return(_a0 error) *MockAccessProviderClient_DeleteAccessProvider_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccessProviderClient_DeleteAccessProvider_Call) RunAndReturn(run func(context.Context, string, ...func(*services.UpdateAccessProviderOptions)) error) *MockAccessProviderClient_DeleteAccessProvider_Call {
	_c.Call.Return(run)
	return _c
}

// ListAccessProviders provides a mock function with given fields: ctx, ops
func (_m *MockAccessProviderClient) ListAccessProviders(ctx context.Context, ops ...func(*services.AccessProviderListOptions)) <-chan schema.ListItem[schema.AccessProvider] {
	_va := make([]interface{}, len(ops))
	for _i := range ops {
		_va[_i] = ops[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListAccessProviders")
	}

	var r0 <-chan schema.ListItem[schema.AccessProvider]
	if rf, ok := ret.Get(0).(func(context.Context, ...func(*services.AccessProviderListOptions)) <-chan schema.ListItem[schema.AccessProvider]); ok {
		r0 = rf(ctx, ops...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan schema.ListItem[schema.AccessProvider])
		}
	}

	return r0
}

// MockAccessProviderClient_ListAccessProviders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAccessProviders'
type MockAccessProviderClient_ListAccessProviders_Call struct {
	*mock.Call
}

// ListAccessProviders is a helper method to define mock.On call
//   - ctx context.Context
//   - ops ...func(*services.AccessProviderListOptions)
func (_e *MockAccessProviderClient_Expecter) ListAccessProviders(ctx interface{}, ops ...interface{}) *MockAccessProviderClient_ListAccessProviders_Call {
	return &MockAccessProviderClient_ListAccessProviders_Call{Call: _e.mock.On("ListAccessProviders",
		append([]interface{}{ctx}, ops...)...)}
}

func (_c *MockAccessProviderClient_ListAccessProviders_Call) Run(run func(ctx context.Context, ops ...func(*services.AccessProviderListOptions))) *MockAccessProviderClient_ListAccessProviders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*services.AccessProviderListOptions), len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(func(*services.AccessProviderListOptions))
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockAccessProviderClient_ListAccessProviders_Call) Return(_a0 <-chan schema.ListItem[schema.AccessProvider]) *MockAccessProviderClient_ListAccessProviders_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccessProviderClient_ListAccessProviders_Call) RunAndReturn(run func(context.Context, ...func(*services.AccessProviderListOptions)) <-chan schema.ListItem[schema.AccessProvider]) *MockAccessProviderClient_ListAccessProviders_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAccessProvider provides a mock function with given fields: ctx, id, ap, ops
func (_m *MockAccessProviderClient) UpdateAccessProvider(ctx context.Context, id string, ap schema.AccessProviderInput, ops ...func(*services.UpdateAccessProviderOptions)) (*schema.AccessProvider, error) {
	_va := make([]interface{}, len(ops))
	for _i := range ops {
		_va[_i] = ops[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id, ap)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccessProvider")
	}

	var r0 *schema.AccessProvider
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, schema.AccessProviderInput, ...func(*services.UpdateAccessProviderOptions)) (*schema.AccessProvider, error)); ok {
		return rf(ctx, id, ap, ops...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, schema.AccessProviderInput, ...func(*services.UpdateAccessProviderOptions)) *schema.AccessProvider); ok {
		r0 = rf(ctx, id, ap, ops...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schema.AccessProvider)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, schema.AccessProviderInput, ...func(*services.UpdateAccessProviderOptions)) error); ok {
		r1 = rf(ctx, id, ap, ops...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccessProviderClient_UpdateAccessProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAccessProvider'
type MockAccessProviderClient_UpdateAccessProvider_Call struct {
	*mock.Call
}

// UpdateAccessProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - ap schema.AccessProviderInput
//   - ops ...func(*services.UpdateAccessProviderOptions)
func (_e *MockAccessProviderClient_Expecter) UpdateAccessProvider(ctx interface{}, id interface{}, ap interface{}, ops ...interface{}) *MockAccessProviderClient_UpdateAccessProvider_Call {
	return &MockAccessProviderClient_UpdateAccessProvider_Call{Call: _e.mock.On("UpdateAccessProvider",
		append([]interface{}{ctx, id, ap}, ops...)...)}
}

func (_c *MockAccessProviderClient_UpdateAccessProvider_Call) Run(run func(ctx context.Context, id string, ap schema.AccessProviderInput, ops ...func(*services.UpdateAccessProviderOptions))) *MockAccessProviderClient_UpdateAccessProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*services.UpdateAccessProviderOptions), len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(func(*services.UpdateAccessProviderOptions))
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(schema.AccessProviderInput), variadicArgs...)
	})
	return _c
}

func (_c *MockAccessProviderClient_UpdateAccessProvider_Call) Return(_a0 *schema.AccessProvider, _a1 error) *MockAccessProviderClient_UpdateAccessProvider_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccessProviderClient_UpdateAccessProvider_Call) RunAndReturn(run func(context.Context, string, schema.AccessProviderInput, ...func(*services.UpdateAccessProviderOptions)) (*schema.AccessProvider, error)) *MockAccessProviderClient_UpdateAccessProvider_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccessProviderClient creates a new instance of MockAccessProviderClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccessProviderClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccessProviderClient {
	mock := &MockAccessProviderClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
